### ISSUE TITLE
Better Tags does not work with the new Anki 2.1.40

### ISSUE THREAD

**Issue by jcsquire** [glutanimate/bettertags-public#19]
#### Problem description

*Open Anki 2.1.40 with Better Tags installed and all other add-ons disabled.  Press "Browse".  Anki throws an exception (a popup error screen) that says:

Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.40 (cf446733) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2021-02-19 09:18:08

Caught exception:
Traceback (most recent call last):
  File "aqt\webview.py", line 35, in cmd
  File "aqt\webview.py", line 124, in _onCmd
  File "aqt\webview.py", line 569, in _onBridgeCmd
  File "aqt\toolbar.py", line 170, in _linkHandler
  File "aqt\toolbar.py", line 188, in _browseLinkHandler
  File "aqt\main.py", line 1056, in onBrowse
  File "aqt\__init__.py", line 100, in open
  File "C:\Users\squirejc\AppData\Roaming\Anki2\addons21\874215009\advancedbrowser\core.py", line 206, in __init__
    origInit(self, mw)
  File "<decorator-gen-24>", line 2, in __init__
  File "anki\hooks.py", line 89, in decorator_wrapper
  File "anki\hooks.py", line 80, in repl
  File "aqt\browser.py", line 600, in __init__
  File "<decorator-gen-22>", line 2, in setupSidebar
  File "anki\hooks.py", line 89, in decorator_wrapper
  File "anki\hooks.py", line 81, in repl
  File "C:\Users\squirejc\AppData\Roaming\Anki2\addons21\bettertags\sidebar\__init__.py", line 43, in onSetupSidebar
    browser.sidebarTree._deferredInit()
AttributeError: 'NewSidebarTreeView' object has no attribute '_deferredInit'

*

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x] I've restarted Anki to see if it helps
 - [x] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [x] I've verified that I use the latest version of Anki by checking at https://apps.ankiweb.net#download
 - [x] I've tried to disable other add-ons to see if there are any interactions present
 - [x] My issue disappears when I hold shift while starting Anki.
 - [x] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### Information about your Anki set-up

*Please fill out the section corresponding with your Anki version:*
2.1.40

##### If you are using Anki 2.1

*Please open Anki, go to Help → About, click on "Copy Debug Info", and paste the result between the backticks below (if the button does not appear you are using an older version of Anki 2.1 and will need to update first):*

```
    
    Anki 2.1.40 (cf446733) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
    Platform: Windows 10
    Flags: frz=True ao=True sv=1
    Add-ons, last update check: 2021-02-19 09:18:08
    
    
    ===Add-ons (active)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    BetterTags ['bettertags', 2020-04-28T11:40, 'None', '']
    Resize images in editor ['1103084694', 2020-08-02T09:04, 'None', mod]
    
    ===IDs of active AnkiWeb add-ons===
    1103084694
    
    ===Add-ons (inactive)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    Advanced Browser ['874215009', 2020-11-08T06:03, 'None', '']
    Anki Simulator ['817108664', 2021-01-30T06:57, 'None', '']
    BetterSearch ['1052724801', 2020-10-25T16:49, 'None', '']
    Customize Sidebar ['1988760596', 2020-01-15T16:01, 'None', '']
    Fastbar- with nightmode support ['46611790', 2021-02-11T12:31, 'None', '']
    Frozen Fields ['516643804', 2020-02-29T23:12, 'None', '']
    Hierarchical Tags 2 ['594329229', 2020-04-11T12:36, 'None', '']
    Image Occlusion Enhanced for Anki 21 alpha ['1374772155', 2020-04-27T22:21, 'None', '']
    Review Heatmap ['review_heatmap', 2020-04-30T09:23, 'None', '']
    Search Everywhere - Ctrl+F Find ['search_everywhere', 2020-03-31T16:13, 'None', '']
    Special Fields ['1102281552', 2021-02-13T17:52, 'None', '']

```

#####  If you are using Anki 2.0

*Please open Anki, go to Help → About, find the two lines starting with `Version:` and `Qt`, and copy-paste them between the backticks below:*

```
Version ⁨2.1.40 (cf446733)⁩
Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
```

*Please fill in details about your operating system (Windows/macOS/Linux, which version):*

- OS: Windows 10
- version: latest

*Please open Anki, go to Tools → Add-ons, take a screenshot of your installed add-ons, and paste it below:*
![image](https://user-images.githubusercontent.com/79332366/108547921-1f06fd00-72b9-11eb-82a4-df57349f5bdf.png)

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.40 (cf446733) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2021-02-19 09:18:08

Caught exception:
Traceback (most recent call last):
  File "aqt\webview.py", line 35, in cmd
  File "aqt\webview.py", line 124, in _onCmd
  File "aqt\webview.py", line 569, in _onBridgeCmd
  File "aqt\toolbar.py", line 170, in _linkHandler
  File "aqt\toolbar.py", line 188, in _browseLinkHandler
  File "aqt\main.py", line 1056, in onBrowse
  File "aqt\__init__.py", line 100, in open
  File "<decorator-gen-4>", line 2, in __init__
  File "anki\hooks.py", line 89, in decorator_wrapper
  File "anki\hooks.py", line 80, in repl
  File "aqt\browser.py", line 600, in __init__
  File "<decorator-gen-2>", line 2, in setupSidebar
  File "anki\hooks.py", line 89, in decorator_wrapper
  File "anki\hooks.py", line 81, in repl
  File "C:\Users\squirejc\AppData\Roaming\Anki2\addons21\bettertags\sidebar\__init__.py", line 43, in onSetupSidebar
    browser.sidebarTree._deferredInit()
AttributeError: 'NewSidebarTreeView' object has no attribute '_deferredInit'

```

**Comment by jenshda** [comment]
Same for me with anki  2.1.40. Cannot open the browser with Better tags enabled

Debug info:
Anki 2.1.40 (cf446733) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Mac 10.16
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2021-05-04 09:07:05
Add-ons possibly involved: ⁨BetterTags, Advanced Browser⁩

Caught exception:
Traceback (most recent call last):
  File "aqt/webview.py", line 35, in cmd
  File "aqt/webview.py", line 124, in _onCmd
  File "aqt/webview.py", line 569, in _onBridgeCmd
  File "aqt/toolbar.py", line 170, in _linkHandler
  File "aqt/toolbar.py", line 188, in _browseLinkHandler
  File "aqt/main.py", line 1056, in onBrowse
  File "aqt/__init__.py", line 100, in open
  File "/Users/jens/Library/Application Support/Anki2/addons21/874215009/advancedbrowser/core.py", line 206, in __init__
    origInit(self, mw)
  File "<decorator-gen-160>", line 2, in __init__
  File "anki/hooks.py", line 89, in decorator_wrapper
  File "anki/hooks.py", line 80, in repl
  File "<decorator-gen-134>", line 2, in __init__
  File "anki/hooks.py", line 89, in decorator_wrapper
  File "anki/hooks.py", line 80, in repl
  File "aqt/browser.py", line 600, in __init__
  File "<decorator-gen-132>", line 2, in setupSidebar
  File "anki/hooks.py", line 89, in decorator_wrapper
  File "anki/hooks.py", line 81, in repl
  File "/Users/jens/Library/Application Support/Anki2/addons21/bettertags/sidebar/__init__.py", line 43, in onSetupSidebar
    browser.sidebarTree._deferredInit()
AttributeError: 'NewSidebarTreeView' object has no attribute '_deferredInit'

**Comment by DNooch381** [comment]
Same here:

Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.40 (cf446733) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Mac 10.16
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2021-06-04 00:45:42
Add-ons possibly involved: ⁨Advanced Browser⁩

Caught exception:
Traceback (most recent call last):
  File "aqt/webview.py", line 35, in cmd
  File "aqt/webview.py", line 124, in _onCmd
  File "aqt/webview.py", line 569, in _onBridgeCmd
  File "aqt/toolbar.py", line 170, in _linkHandler
  File "aqt/toolbar.py", line 188, in _browseLinkHandler
  File "aqt/main.py", line 1056, in onBrowse
  File "aqt/__init__.py", line 100, in open
  File "/Users/home_dylanantonacci/Library/Application Support/Anki2/addons21/874215009/advancedbrowser/core.py", line 206, in __init__
    origInit(self, mw)
TypeError: newBrowserInit() takes 2 positional arguments but 3 were given

**Comment by Michaelpogi0912** [comment]
How can download Better Tag in Anki? @DNooch381 @jcsquire @jenshda @glutanimate ...Thanks in Advance
